### ISSUE TITLE
如何使用less？

### ISSUE THREAD

**Issue by luojinghui** [wechat-miniprogram/miniprogram-custom-component#1]
我在config.js中修改设置：
```js
  wxss: {
    less: true, // compile wxss with less
    sourcemap: false, // source map for less
  },
```
但是在wxss文件中，使用less语法控制台报错？

**Comment by JuneAndGreen** [comment]
编译时报错么？报的什么错？

**Comment by luojinghui** [comment]
@JuneAndGreen 
我在config开启了less为true，然后在page页面的wxss文件中书写了less语法，小程序提示：
![image](https://user-images.githubusercontent.com/12367406/48883996-6b0a3380-ee5d-11e8-80b8-14b8d73a34fe.png)
代码片段：
```less
.xylink {
	&-container {
		background-color: #1f1f25;
		height: 100vh;
		width: 100vw;
		color: #fff;	
	}
}
```
貌似没有将less转换成wxss语法格式。

请问是我配置还是写的有问题吗？
