### ISSUE TITLE
编译wxss calc属性计算出错？

### ISSUE THREAD

**Issue by luojinghui** [wechat-miniprogram/miniprogram-custom-component#3]
期望值：
```css
.xy-pause-name-box {
  left: calc(47% - 50rpx);
}
```
输出：
```css
.xy-pause-name-box {
  left: calc(-3%);
}
```

求解，多谢
